# Generated by Django 3.1.4 on 2020-12-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.CharField(default='1970-01-01', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='graduate_time',
            field=models.CharField(default='1970-01-01', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='00001', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='工程师', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job2',
            field=models.CharField(default='工程师', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_join_time',
            field=models.CharField(default='1970-01-01', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_number',
            field=models.CharField(default='00001', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='job_time',
            field=models.CharField(default='1970-01-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='第一次登陆', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='17890987654', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='political_landscape',
            field=models.CharField(default='群众', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='political_time',
            field=models.CharField(default='1970-01-01', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='北京大学', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='schooling',
            field=models.CharField(default='本科', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='team_belong',
            field=models.CharField(default='OOS', max_length=20),
        ),
    ]
