# Generated by Django 3.1.4 on 2020-12-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201207_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job2',
        ),
        migrations.AddField(
            model_name='user',
            name='job_2',
            field=models.CharField(default='员工', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='00001', max_length=30),
        ),
    ]
